//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHELLOSERVICES_COMMTIME_H_
#define DOMAINHELLOSERVICES_COMMTIME_H_

#include "DomainHelloServices/CommTimeCore.hh"

namespace DomainHelloServices {
		
class CommTime : public CommTimeCore {
	public:
		// default constructors
		CommTime();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommTime(const unsigned long int &sec, const unsigned long int &usec);
		
		CommTime(const CommTimeCore &commTime);
		CommTime(const DATATYPE &commTime);
		virtual ~CommTime();
		
		// use framework specific getter and setter methods from core (base) class
		using CommTimeCore::get;
		using CommTimeCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommTime &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace DomainHelloServices */
#endif /* DOMAINHELLOSERVICES_COMMTIME_H_ */
