//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMFILEREADREQUEST_CORE_H_
#define COMMBASICOBJECTS_COMMFILEREADREQUEST_CORE_H_

#include "CommBasicObjects/CommFileReadRequestData.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommBasicObjects {
	
class CommFileReadRequestCore {
protected:
	// data structure
	CommBasicObjectsIDL::CommFileReadRequest idl_CommFileReadRequest;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommBasicObjectsIDL::CommFileReadRequest DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommFileReadRequestCore();
	CommFileReadRequestCore(const DATATYPE &data);
	// default destructor
	virtual ~CommFileReadRequestCore();
	
	const DATATYPE& get() const { return idl_CommFileReadRequest; }
	operator const DATATYPE&() const { return idl_CommFileReadRequest; }
	DATATYPE& set() { return idl_CommFileReadRequest; }

	static inline std::string identifier(void) { return "CommBasicObjects::CommFileReadRequest"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Filename
	inline std::string getFilename() const { return idl_CommFileReadRequest.filename; }
	inline CommFileReadRequestCore& setFilename(const std::string &filename) { idl_CommFileReadRequest.filename = filename; return *this; }
	
	// getter and setter for element CompressFile
	inline bool getCompressFile() const { return idl_CommFileReadRequest.compressFile; }
	inline CommFileReadRequestCore& setCompressFile(const bool &compressFile) { idl_CommFileReadRequest.compressFile = compressFile; return *this; }
};

} /* namespace CommBasicObjects */
#endif /* COMMBASICOBJECTS_COMMFILEREADREQUEST_CORE_H_ */
