//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMBASESTATE_DATA_H_
#define COMMBASICOBJECTS_COMMBASESTATE_DATA_H_

#include "CommBasicObjects/CommBatteryLevelData.hh"
#include "CommBasicObjects/CommBaseVelocityData.hh"
#include "CommBasicObjects/CommTimeStampData.hh"
#include "CommBasicObjects/CommBasePoseData.hh"


namespace CommBasicObjectsIDL 
{
	struct CommBaseState
	{
		CommBasicObjectsIDL::CommTimeStamp timeStamp;
		CommBasicObjectsIDL::CommBasePose basePose;
		CommBasicObjectsIDL::CommBasePose baseOdomPose;
		CommBasicObjectsIDL::CommBaseVelocity baseVelocity;
		CommBasicObjectsIDL::CommBaseVelocity baseOdomVelocity;
		CommBasicObjectsIDL::CommBatteryLevel batteryState;
  	};
};

#endif /* COMMBASICOBJECTS_COMMBASESTATE_DATA_H_ */
