//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMPOSE3D_DATA_H_
#define COMMBASICOBJECTS_COMMPOSE3D_DATA_H_

#include "CommBasicObjects/CommPosition3dData.hh"
#include "CommBasicObjects/CommOrientation3dData.hh"


namespace CommBasicObjectsIDL 
{
	struct CommPose3d
	{
		CommBasicObjectsIDL::CommPosition3d position;
		CommBasicObjectsIDL::CommOrientation3d orientation;
  	};
};

#endif /* COMMBASICOBJECTS_COMMPOSE3D_DATA_H_ */
