//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMFILEMOVEREVENTRESULT_CORE_H_
#define COMMBASICOBJECTS_COMMFILEMOVEREVENTRESULT_CORE_H_

#include "CommBasicObjects/CommFileMoverEventResultData.hh"
#include "CommBasicObjects/enumFileMoverEventType.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommBasicObjects {
	
class CommFileMoverEventResultCore {
protected:
	// data structure
	CommBasicObjectsIDL::CommFileMoverEventResult idl_CommFileMoverEventResult;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommBasicObjectsIDL::CommFileMoverEventResult DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommFileMoverEventResultCore();
	CommFileMoverEventResultCore(const DATATYPE &data);
	// default destructor
	virtual ~CommFileMoverEventResultCore();
	
	const DATATYPE& get() const { return idl_CommFileMoverEventResult; }
	operator const DATATYPE&() const { return idl_CommFileMoverEventResult; }
	DATATYPE& set() { return idl_CommFileMoverEventResult; }

	static inline std::string identifier(void) { return "CommBasicObjects::CommFileMoverEventResult"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element State
	inline CommBasicObjects::FileMoverEventType getState() const { return CommBasicObjects::FileMoverEventType(idl_CommFileMoverEventResult.state); }
	inline CommFileMoverEventResultCore& setState(const CommBasicObjects::FileMoverEventType &state) { idl_CommFileMoverEventResult.state = state; return *this; }
};

} /* namespace CommBasicObjects */
#endif /* COMMBASICOBJECTS_COMMFILEMOVEREVENTRESULT_CORE_H_ */
