//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommBasicObjects/CommBatteryParameterCore.hh"

// serialization/deserialization operators
//#include "CommBasicObjects/CommBatteryParameterACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommBasicObjects 
{
	const char* CommBatteryParameterCore::getCompiledHash()
	{
		return CommBasicObjectsIDL::REPO_HASH;
	}
	
	void CommBatteryParameterCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void CommBatteryParameterCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommBatteryParameterCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t CommBatteryParameterCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.upperThreshold);
		boost::hash_combine(seed, data.lowerThreshold);
		boost::hash_combine(seed, data.desiredState);
		boost::hash_combine(seed, data.currentState);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommBatteryParameterCore::CommBatteryParameterCore()
	:	idl_CommBatteryParameter()
	{  
		setUpperThreshold(0.0);
		setLowerThreshold(0.0);
		setDesiredState(CommBasicObjects::ComparisonState());
		setCurrentState(CommBasicObjects::ComparisonState());
	}
	
	CommBatteryParameterCore::CommBatteryParameterCore(const DATATYPE &data)
	:	idl_CommBatteryParameter(data)
	{  }

	CommBatteryParameterCore::~CommBatteryParameterCore()
	{  }
	
	void CommBatteryParameterCore::to_ostream(std::ostream &os) const
	{
	  os << "CommBatteryParameter(";
	  os << getUpperThreshold() << " ";
	  os << getLowerThreshold() << " ";
	  getDesiredState().to_ostream(os);
	  getCurrentState().to_ostream(os);
	  os << ") ";
	}
	
	// convert to xml stream
	void CommBatteryParameterCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<upperThreshold>" << getUpperThreshold() << "</upperThreshold>";
		os << indent << "<lowerThreshold>" << getLowerThreshold() << "</lowerThreshold>";
		os << indent << "<desiredState>";
		getDesiredState().to_xml(os, indent);
		os << indent << "</desiredState>";
		os << indent << "<currentState>";
		getCurrentState().to_xml(os, indent);
		os << indent << "</currentState>";
	}
	
	// restore from xml stream
	void CommBatteryParameterCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_upperThreshold("<upperThreshold>");
		static const Smart::KnuthMorrisPratt kmp_lowerThreshold("<lowerThreshold>");
		static const Smart::KnuthMorrisPratt kmp_desiredState("<desiredState>");
		static const Smart::KnuthMorrisPratt kmp_currentState("<currentState>");
		
		if(kmp_upperThreshold.search(is)) {
			double upperThresholdItem;
			is >> upperThresholdItem;
			setUpperThreshold(upperThresholdItem);
		}
		if(kmp_lowerThreshold.search(is)) {
			double lowerThresholdItem;
			is >> lowerThresholdItem;
			setLowerThreshold(lowerThresholdItem);
		}
		if(kmp_desiredState.search(is)) {
			CommBasicObjects::ComparisonState desiredStateItem;
			desiredStateItem.from_xml(is);
			setDesiredState(desiredStateItem);
		}
		if(kmp_currentState.search(is)) {
			CommBasicObjects::ComparisonState currentStateItem;
			currentStateItem.from_xml(is);
			setCurrentState(currentStateItem);
		}
	}
	
	/*
	void CommBatteryParameterCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommBasicObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommBasicObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommBatteryParameterACE.hh)
		cdr << idl_CommBatteryParameter;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommBatteryParameter);
		cdr << data_hash;
		// std::cout << "CommBatteryParameterCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommBatteryParameterCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommBasicObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommBatteryParameterACE.hh)
		cdr >> idl_CommBatteryParameter;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommBatteryParameter);
		assert(data_hash == own_hash);
		// std::cout << "CommBatteryParameterCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommBasicObjects */
