//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMDATAFILE_DATA_H_
#define COMMBASICOBJECTS_COMMDATAFILE_DATA_H_

#include "CommBasicObjects/CommTimeStampData.hh"

#include <vector>
#include <string>

namespace CommBasicObjectsIDL 
{
	typedef std::vector<char> CommDataFile_data_type;
	struct CommDataFile
	{
		std::string filename;
		unsigned int filesize;
		CommBasicObjectsIDL::CommTimeStamp timestamp;
		CommDataFile_data_type data;
		bool valid;
  	};
};

#endif /* COMMBASICOBJECTS_COMMDATAFILE_DATA_H_ */
