//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommBasicObjects/CommJoystickACE.hh"
#include <ace/SString.h>

// serialization operator for element CommJoystick
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommBasicObjectsIDL::CommJoystick &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element xpos
	good_bit = good_bit && cdr.write_short(data.xpos);
	// serialize list-element ypos
	good_bit = good_bit && cdr.write_short(data.ypos);
	// serialize list-element x2pos
	good_bit = good_bit && cdr.write_short(data.x2pos);
	// serialize list-element y2pos
	good_bit = good_bit && cdr.write_short(data.y2pos);
	// serialize list-element buttons
	good_bit = good_bit && cdr.write_ushort(data.buttons);
	
	return good_bit;
}

// de-serialization operator for element CommJoystick
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommBasicObjectsIDL::CommJoystick &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element xpos
	good_bit = good_bit && cdr.read_short(data.xpos);
	// deserialize type element ypos
	good_bit = good_bit && cdr.read_short(data.ypos);
	// deserialize type element x2pos
	good_bit = good_bit && cdr.read_short(data.x2pos);
	// deserialize type element y2pos
	good_bit = good_bit && cdr.read_short(data.y2pos);
	// deserialize type element buttons
	good_bit = good_bit && cdr.read_ushort(data.buttons);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommJoystick
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommBasicObjects::CommJoystick &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommJoystick
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommBasicObjects::CommJoystick &obj)
{
	return cdr >> obj.set();
}
