//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommBasicObjects/CommBatteryLevelCore.hh"

// serialization/deserialization operators
//#include "CommBasicObjects/CommBatteryLevelACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommBasicObjects 
{
	const char* CommBatteryLevelCore::getCompiledHash()
	{
		return CommBasicObjectsIDL::REPO_HASH;
	}
	
	void CommBatteryLevelCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for CommBasicObjects::CommTimeStamp(idl_CommBatteryLevel.lifeTime)
		CommBasicObjects::CommTimeStamp::getAllHashValues(hashes);
		// get hash value(s) for CommBasicObjects::CommTimeStamp(idl_CommBatteryLevel.timeStamp)
		CommBasicObjects::CommTimeStamp::getAllHashValues(hashes);
	}
	
	void CommBatteryLevelCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommBatteryLevelCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for CommBasicObjects::CommTimeStamp(idl_CommBatteryLevel.lifeTime)
		CommBasicObjects::CommTimeStamp::checkAllHashValues(hashes);
		// check hash value(s) for CommBasicObjects::CommTimeStamp(idl_CommBatteryLevel.timeStamp)
		CommBasicObjects::CommTimeStamp::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommBatteryLevelCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.potential);
		boost::hash_combine(seed, data.chargeLevel);
		seed += CommBasicObjects::CommTimeStamp::generateDataHash(data.lifeTime);
		seed += CommBasicObjects::CommTimeStamp::generateDataHash(data.timeStamp);
		boost::hash_combine(seed, data.current);
		boost::hash_combine(seed, data.externalPower);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommBatteryLevelCore::CommBatteryLevelCore()
	:	idl_CommBatteryLevel()
	{  
		setPotential(0.0);
		setChargeLevel(0);
		setLifeTime(CommBasicObjects::CommTimeStamp());
		setTimeStamp(CommBasicObjects::CommTimeStamp());
		setCurrent(0.0);
		setExternalPower(false);
	}
	
	CommBatteryLevelCore::CommBatteryLevelCore(const DATATYPE &data)
	:	idl_CommBatteryLevel(data)
	{  }

	CommBatteryLevelCore::~CommBatteryLevelCore()
	{  }
	
	void CommBatteryLevelCore::to_ostream(std::ostream &os) const
	{
	  os << "CommBatteryLevel(";
	  os << getPotential() << " ";
	  os << getChargeLevel() << " ";
	  getLifeTime().to_ostream(os);
	  getTimeStamp().to_ostream(os);
	  os << getCurrent() << " ";
	  os << getExternalPower() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void CommBatteryLevelCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<potential>" << getPotential() << "</potential>";
		os << indent << "<chargeLevel>" << getChargeLevel() << "</chargeLevel>";
		os << indent << "<lifeTime>";
		getLifeTime().to_xml(os, indent);
		os << indent << "</lifeTime>";
		os << indent << "<timeStamp>";
		getTimeStamp().to_xml(os, indent);
		os << indent << "</timeStamp>";
		os << indent << "<current>" << getCurrent() << "</current>";
		os << indent << "<externalPower>" << getExternalPower() << "</externalPower>";
	}
	
	// restore from xml stream
	void CommBatteryLevelCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_potential("<potential>");
		static const Smart::KnuthMorrisPratt kmp_chargeLevel("<chargeLevel>");
		static const Smart::KnuthMorrisPratt kmp_lifeTime("<lifeTime>");
		static const Smart::KnuthMorrisPratt kmp_timeStamp("<timeStamp>");
		static const Smart::KnuthMorrisPratt kmp_current("<current>");
		static const Smart::KnuthMorrisPratt kmp_externalPower("<externalPower>");
		
		if(kmp_potential.search(is)) {
			double potentialItem;
			is >> potentialItem;
			setPotential(potentialItem);
		}
		if(kmp_chargeLevel.search(is)) {
			int chargeLevelItem;
			is >> chargeLevelItem;
			setChargeLevel(chargeLevelItem);
		}
		if(kmp_lifeTime.search(is)) {
			CommBasicObjects::CommTimeStamp lifeTimeItem;
			lifeTimeItem.from_xml(is);
			setLifeTime(lifeTimeItem);
		}
		if(kmp_timeStamp.search(is)) {
			CommBasicObjects::CommTimeStamp timeStampItem;
			timeStampItem.from_xml(is);
			setTimeStamp(timeStampItem);
		}
		if(kmp_current.search(is)) {
			double currentItem;
			is >> currentItem;
			setCurrent(currentItem);
		}
		if(kmp_externalPower.search(is)) {
			bool externalPowerItem;
			is >> externalPowerItem;
			setExternalPower(externalPowerItem);
		}
	}
	
	/*
	void CommBatteryLevelCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommBasicObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommBasicObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommBatteryLevelACE.hh)
		cdr << idl_CommBatteryLevel;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommBatteryLevel);
		cdr << data_hash;
		// std::cout << "CommBatteryLevelCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommBatteryLevelCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommBasicObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommBatteryLevelACE.hh)
		cdr >> idl_CommBatteryLevel;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommBatteryLevel);
		assert(data_hash == own_hash);
		// std::cout << "CommBatteryLevelCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommBasicObjects */
