//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMULTRASONICSCAN_DATA_H_
#define COMMBASICOBJECTS_COMMULTRASONICSCAN_DATA_H_

#include "CommBasicObjects/CommTimeStampData.hh"
#include "CommBasicObjects/CommPose3dData.hh"

#include <vector>

namespace CommBasicObjectsIDL 
{
	typedef std::vector<CommBasicObjectsIDL::CommPose3d> CommUltrasonicScan_scanPoints_type;
	typedef std::vector<double> CommUltrasonicScan_intensities_type;
	struct CommUltrasonicScan
	{
		CommBasicObjectsIDL::CommTimeStamp timeStamp;
		CommUltrasonicScan_scanPoints_type scanPoints;
		CommUltrasonicScan_intensities_type intensities;
  	};
};

#endif /* COMMBASICOBJECTS_COMMULTRASONICSCAN_DATA_H_ */
