//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMDEVICEPOSESTATE_CORE_H_
#define COMMBASICOBJECTS_COMMDEVICEPOSESTATE_CORE_H_

#include "CommBasicObjects/CommDevicePoseStateData.hh"
#include "CommBasicObjects/CommPose3d.hh"
#include "CommBasicObjects/CommBaseState.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommBasicObjects {
	
class CommDevicePoseStateCore {
protected:
	// data structure
	CommBasicObjectsIDL::CommDevicePoseState idl_CommDevicePoseState;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommBasicObjectsIDL::CommDevicePoseState DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommDevicePoseStateCore();
	CommDevicePoseStateCore(const DATATYPE &data);
	// default destructor
	virtual ~CommDevicePoseStateCore();
	
	const DATATYPE& get() const { return idl_CommDevicePoseState; }
	operator const DATATYPE&() const { return idl_CommDevicePoseState; }
	DATATYPE& set() { return idl_CommDevicePoseState; }

	static inline std::string identifier(void) { return "CommBasicObjects::CommDevicePoseState"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element StateBase
	inline CommBasicObjects::CommBaseState getStateBase() const { return CommBasicObjects::CommBaseState(idl_CommDevicePoseState.stateBase); }
	inline CommDevicePoseStateCore& setStateBase(const CommBasicObjects::CommBaseState &stateBase) { idl_CommDevicePoseState.stateBase = stateBase; return *this; }
	
	// getter and setter for element DevicePose
	inline CommBasicObjects::CommPose3d getDevicePose() const { return CommBasicObjects::CommPose3d(idl_CommDevicePoseState.devicePose); }
	inline CommDevicePoseStateCore& setDevicePose(const CommBasicObjects::CommPose3d &devicePose) { idl_CommDevicePoseState.devicePose = devicePose; return *this; }
};

} /* namespace CommBasicObjects */
#endif /* COMMBASICOBJECTS_COMMDEVICEPOSESTATE_CORE_H_ */
