//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_COMMIMUDATA_DATA_H_
#define COMMBASICOBJECTS_COMMIMUDATA_DATA_H_



namespace CommBasicObjectsIDL 
{
	struct CommIMUData
	{
		unsigned short timestamp;
		double temperature;
		double accelerometer_x;
		double accelerometer_y;
		double accelerometer_z;
		double gyroscope_x;
		double gyroscope_y;
		double gyroscope_z;
		double magnetometer_x;
		double magnetometer_y;
		double magnetometer_z;
		double roll;
		double pitch;
		double yaw;
  	};
};

#endif /* COMMBASICOBJECTS_COMMIMUDATA_DATA_H_ */
