//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_FILETYPE_ENUM_H_
#define COMMBASICOBJECTS_FILETYPE_ENUM_H_

#include <CommBasicObjects/enumFileTypeData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommBasicObjects {
	
	class FileType {
	private:
		CommBasicObjectsIDL::FileType value;
		
	public:
		enum ENUM_FileType {
			ENUM_VALUE_UNDEFINED = 0,
			FILE_REGULAR = 1,
			FILE_DIRECTORY = 2
		};
		
		// default constructor
		FileType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		FileType(ENUM_FileType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		FileType(CommBasicObjectsIDL::FileType e) {
			value = e;
		}
		
		//const CommBasicObjectsIDL::FileType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_FileType() const {
			return static_cast<ENUM_FileType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_FileType t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case FILE_REGULAR:
					result = "FileType::FILE_REGULAR";
					break;
				case FILE_DIRECTORY:
					result = "FileType::FILE_DIRECTORY";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const FileType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
