//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_LASERSCANPOINT_CORE_H_
#define COMMBASICOBJECTS_LASERSCANPOINT_CORE_H_

#include "CommBasicObjects/LaserScanPointData.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommBasicObjects {
	
class LaserScanPointCore {
protected:
	// data structure
	CommBasicObjectsIDL::LaserScanPoint idl_LaserScanPoint;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommBasicObjectsIDL::LaserScanPoint DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	LaserScanPointCore();
	LaserScanPointCore(const DATATYPE &data);
	// default destructor
	virtual ~LaserScanPointCore();
	
	const DATATYPE& get() const { return idl_LaserScanPoint; }
	operator const DATATYPE&() const { return idl_LaserScanPoint; }
	DATATYPE& set() { return idl_LaserScanPoint; }

	static inline std::string identifier(void) { return "CommBasicObjects::LaserScanPoint"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Index
	inline unsigned short getIndex() const { return idl_LaserScanPoint.index; }
	inline LaserScanPointCore& setIndex(const unsigned short &index) { idl_LaserScanPoint.index = index; return *this; }
	
	// getter and setter for element Distance
	inline unsigned short getDistance() const { return idl_LaserScanPoint.distance; }
	inline LaserScanPointCore& setDistance(const unsigned short &distance) { idl_LaserScanPoint.distance = distance; return *this; }
	
	// getter and setter for element Intensity
	inline unsigned char getIntensity() const { return idl_LaserScanPoint.intensity; }
	inline LaserScanPointCore& setIntensity(const unsigned char &intensity) { idl_LaserScanPoint.intensity = intensity; return *this; }
};

} /* namespace CommBasicObjects */
#endif /* COMMBASICOBJECTS_LASERSCANPOINT_CORE_H_ */
