//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ROSUr_msgs/Ur_msgs_DigitalACE.hh"
#include <ace/SString.h>

// serialization operator for element Ur_msgs_Digital
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSUr_msgsIDL::Ur_msgs_Digital &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element pin
	good_bit = good_bit && cdr.write_octet(data.pin);
	// serialize list-element state
	good_bit = good_bit && cdr.write_boolean(data.state);
	
	return good_bit;
}

// de-serialization operator for element Ur_msgs_Digital
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSUr_msgsIDL::Ur_msgs_Digital &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element pin
	good_bit = good_bit && cdr.read_octet(data.pin);
	// deserialize type element state
	good_bit = good_bit && cdr.read_boolean(data.state);
	
	return good_bit;
}

// serialization operator for CommunicationObject Ur_msgs_Digital
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSUr_msgs::Ur_msgs_Digital &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject Ur_msgs_Digital
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSUr_msgs::Ur_msgs_Digital &obj)
{
	return cdr >> obj.set();
}
