//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSUR_MSGS_UR_MSGS_ANALOG_DATA_H_
#define ROSUR_MSGS_UR_MSGS_ANALOG_DATA_H_



namespace ROSUr_msgsIDL 
{
	struct Ur_msgs_Analog
	{
		unsigned char pin;
		unsigned char domain;
		float state;
  	};
};

#endif /* ROSUR_MSGS_UR_MSGS_ANALOG_DATA_H_ */
