//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "SetBoolQueryServiceAnswHandler.hh"
#include "StringServiceQuery.hh"

SetBoolQueryServiceAnswHandler::SetBoolQueryServiceAnswHandler(IQueryServer *server)
:	SetBoolQueryServiceAnswHandlerCore(server)
{
	
}


void SetBoolQueryServiceAnswHandler::handleQuery(const Smart::QueryIdPtr &id, const ROSRos_core::Std_srvs_SetBoolRequest& request) 
{
	ROSRos_core::Std_srvs_SetBoolResponse answer;
	
	if (request.getData()){
		answer.setMessage("I got TRUE");
		answer.setSuccess(true);
	} else{
		answer.setMessage("I got FALSE");
		answer.setSuccess(true);
	}
	// implement your query handling logic here and fill in the answer object
	
	this->server->answer(id, answer);
}
