//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSROS_CORE_STD_MSGS_EMPTY_ACE_H_
#define ROSROS_CORE_STD_MSGS_EMPTY_ACE_H_

#include "ROSRos_core/Std_msgs_Empty.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure Std_msgs_Empty
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSRos_coreIDL::Std_msgs_Empty &data);

// de-serialization operator for DataStructure Std_msgs_Empty
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSRos_coreIDL::Std_msgs_Empty &data);

// serialization operator for CommunicationObject Std_msgs_Empty
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSRos_core::Std_msgs_Empty &obj);

// de-serialization operator for CommunicationObject Std_msgs_Empty
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSRos_core::Std_msgs_Empty &obj);

#endif /* ROSROS_CORE_STD_MSGS_EMPTY_ACE_H_ */
