//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSUR_MSGS_UR_MSGS_SETSPEEDSLIDERFRACTIONRESPONSE_H_
#define ROSUR_MSGS_UR_MSGS_SETSPEEDSLIDERFRACTIONRESPONSE_H_

#include "ROSUr_msgs/Ur_msgs_SetSpeedSliderFractionResponseCore.hh"

namespace ROSUr_msgs {
		
class Ur_msgs_SetSpeedSliderFractionResponse : public Ur_msgs_SetSpeedSliderFractionResponseCore {
	public:
		// default constructors
		Ur_msgs_SetSpeedSliderFractionResponse();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// Ur_msgs_SetSpeedSliderFractionResponse(const bool &success);
		
		Ur_msgs_SetSpeedSliderFractionResponse(const Ur_msgs_SetSpeedSliderFractionResponseCore &ur_msgs_SetSpeedSliderFractionResponse);
		Ur_msgs_SetSpeedSliderFractionResponse(const DATATYPE &ur_msgs_SetSpeedSliderFractionResponse);
		virtual ~Ur_msgs_SetSpeedSliderFractionResponse();
		
		// use framework specific getter and setter methods from core (base) class
		using Ur_msgs_SetSpeedSliderFractionResponseCore::get;
		using Ur_msgs_SetSpeedSliderFractionResponseCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const Ur_msgs_SetSpeedSliderFractionResponse &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace ROSUr_msgs */
#endif /* ROSUR_MSGS_UR_MSGS_SETSPEEDSLIDERFRACTIONRESPONSE_H_ */
