//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "Cob4BaseInit.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "Cob4BaseInitAcePortFactory.hh"


// initialize static singleton pointer to zero
Cob4BaseInit* Cob4BaseInit::_cob4BaseInit = 0;

// constructor
Cob4BaseInit::Cob4BaseInit()
{
	std::cout << "constructor of Cob4BaseInit\n";
	
	// set all pointer members to NULL
	sendInitRequest_activity = NULL;
	sendInitRequest_activityTrigger = NULL;
	triggerQueryServiceReq = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "Cob4BaseInit";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.triggerQueryServiceReq.initialConnect = false;
	connections.triggerQueryServiceReq.wiringName = "TriggerQueryServiceReq";
	connections.triggerQueryServiceReq.serverName = "unknown";
	connections.triggerQueryServiceReq.serviceName = "unknown";
	connections.triggerQueryServiceReq.interval = 1;
	connections.triggerQueryServiceReq.roboticMiddleware = "ACE_SmartSoft";
	connections.sendInitRequest_activity.minActFreq = 0.0;
	connections.sendInitRequest_activity.maxActFreq = 0.0;
	// scheduling default parameters
	connections.sendInitRequest_activity.scheduler = "DEFAULT";
	connections.sendInitRequest_activity.priority = -1;
	connections.sendInitRequest_activity.cpuAffinity = -1;
	
	// initialize members of Cob4BaseInitROSExtension
	
	// initialize members of OpcUaBackendComponentGeneratorExtension
	
	// initialize members of PlainOpcUaCob4BaseInitExtension
	
}

void Cob4BaseInit::addPortFactory(const std::string &name, Cob4BaseInitPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void Cob4BaseInit::addExtension(Cob4BaseInitExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* Cob4BaseInit::getComponentImpl()
{
	return dynamic_cast<Cob4BaseInitAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void Cob4BaseInit::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode Cob4BaseInit::connectTriggerQueryServiceReq(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	if(connections.triggerQueryServiceReq.initialConnect == false) {
		return Smart::SMART_OK;
	}
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = triggerQueryServiceReq->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->triggerQueryServiceReq->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode Cob4BaseInit::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectTriggerQueryServiceReq(connections.triggerQueryServiceReq.serverName, connections.triggerQueryServiceReq.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void Cob4BaseInit::startAllTasks() {
	// start task SendInitRequest_activity
	if(connections.sendInitRequest_activity.scheduler != "DEFAULT") {
		ACE_Sched_Params sendInitRequest_activity_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.sendInitRequest_activity.scheduler == "FIFO") {
			sendInitRequest_activity_SchedParams.policy(ACE_SCHED_FIFO);
			sendInitRequest_activity_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.sendInitRequest_activity.scheduler == "RR") {
			sendInitRequest_activity_SchedParams.policy(ACE_SCHED_RR);
			sendInitRequest_activity_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		sendInitRequest_activity->start(sendInitRequest_activity_SchedParams, connections.sendInitRequest_activity.cpuAffinity);
	} else {
		sendInitRequest_activity->start();
	}
}

/**
 * Start all timers contained in this component
 */
void Cob4BaseInit::startAllTimers() {
}


Smart::TaskTriggerSubject* Cob4BaseInit::getInputTaskTriggerFromString(const std::string &client)
{
	
	return NULL;
}


void Cob4BaseInit::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of Cob4BaseInitROSExtension
		
		// initializations of OpcUaBackendComponentGeneratorExtension
		
		// initializations of PlainOpcUaCob4BaseInitExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		Cob4BaseInitPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<Cob4BaseInitAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition Cob4BaseInit is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		
		// create client ports
		triggerQueryServiceReq = portFactoryRegistry[connections.triggerQueryServiceReq.roboticMiddleware]->createTriggerQueryServiceReq();
		
		// create InputTaskTriggers and UpcallManagers
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.triggerQueryServiceReq.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::QueryClient<ROSRos_core::Std_srvs_TriggerRequest, ROSRos_core::Std_srvs_TriggerResponse>*>(triggerQueryServiceReq)->add(wiringSlave, connections.triggerQueryServiceReq.wiringName);
		}
		
		
		
		// create Task SendInitRequest_activity
		sendInitRequest_activity = new SendInitRequest_activity(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.sendInitRequest_activity.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.sendInitRequest_activity.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(sendInitRequest_activity);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				sendInitRequest_activityTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task SendInitRequest_activity" << std::endl;
			}
		} else if(connections.sendInitRequest_activity.trigger == "DataTriggered") {
			sendInitRequest_activityTrigger = getInputTaskTriggerFromString(connections.sendInitRequest_activity.inPortRef);
			if(sendInitRequest_activityTrigger != NULL) {
				sendInitRequest_activityTrigger->attach(sendInitRequest_activity, connections.sendInitRequest_activity.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.sendInitRequest_activity.inPortRef << " as activation source for Task SendInitRequest_activity" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void Cob4BaseInit::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void Cob4BaseInit::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(sendInitRequest_activityTrigger != NULL){
		sendInitRequest_activityTrigger->detach(sendInitRequest_activity);
		delete sendInitRequest_activity;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers

	// destroy client ports
	delete triggerQueryServiceReq;

	// destroy server ports
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of Cob4BaseInitROSExtension
	
	// destruction of OpcUaBackendComponentGeneratorExtension
	
	// destruction of PlainOpcUaCob4BaseInitExtension
	
}

void Cob4BaseInit::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("Cob4BaseInit.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load Cob4BaseInit.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: Cob4BaseInit.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client TriggerQueryServiceReq
		parameter.getBoolean("TriggerQueryServiceReq", "initialConnect", connections.triggerQueryServiceReq.initialConnect);
		parameter.getString("TriggerQueryServiceReq", "serviceName", connections.triggerQueryServiceReq.serviceName);
		parameter.getString("TriggerQueryServiceReq", "serverName", connections.triggerQueryServiceReq.serverName);
		parameter.getString("TriggerQueryServiceReq", "wiringName", connections.triggerQueryServiceReq.wiringName);
		if(parameter.checkIfParameterExists("TriggerQueryServiceReq", "roboticMiddleware")) {
			parameter.getString("TriggerQueryServiceReq", "roboticMiddleware", connections.triggerQueryServiceReq.roboticMiddleware);
		}
		
		
		// load parameters for task SendInitRequest_activity
		parameter.getDouble("SendInitRequest_activity", "minActFreqHz", connections.sendInitRequest_activity.minActFreq);
		parameter.getDouble("SendInitRequest_activity", "maxActFreqHz", connections.sendInitRequest_activity.maxActFreq);
		parameter.getString("SendInitRequest_activity", "triggerType", connections.sendInitRequest_activity.trigger);
		if(connections.sendInitRequest_activity.trigger == "PeriodicTimer") {
			parameter.getDouble("SendInitRequest_activity", "periodicActFreqHz", connections.sendInitRequest_activity.periodicActFreq);
		} else if(connections.sendInitRequest_activity.trigger == "DataTriggered") {
			parameter.getString("SendInitRequest_activity", "inPortRef", connections.sendInitRequest_activity.inPortRef);
			parameter.getInteger("SendInitRequest_activity", "prescale", connections.sendInitRequest_activity.prescale);
		}
		if(parameter.checkIfParameterExists("SendInitRequest_activity", "scheduler")) {
			parameter.getString("SendInitRequest_activity", "scheduler", connections.sendInitRequest_activity.scheduler);
		}
		if(parameter.checkIfParameterExists("SendInitRequest_activity", "priority")) {
			parameter.getInteger("SendInitRequest_activity", "priority", connections.sendInitRequest_activity.priority);
		}
		if(parameter.checkIfParameterExists("SendInitRequest_activity", "cpuAffinity")) {
			parameter.getInteger("SendInitRequest_activity", "cpuAffinity", connections.sendInitRequest_activity.cpuAffinity);
		}
		
		// load parameters for Cob4BaseInitROSExtension
		
		// load parameters for OpcUaBackendComponentGeneratorExtension
		
		// load parameters for PlainOpcUaCob4BaseInitExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
