//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef COMPONENTROSCOB4_3_ACE_PORTFACTORY_HH_
#define COMPONENTROSCOB4_3_ACE_PORTFACTORY_HH_

// include ACE/SmartSoft component implementation
#include "ComponentRoscob4_3Impl.hh"

// include the main component-definition class
#include "ComponentRoscob4_3PortFactoryInterface.hh"

class ComponentRoscob4_3AcePortFactory: public ComponentRoscob4_3PortFactoryInterface
{
private:
	ComponentRoscob4_3Impl *componentImpl;
public:
	ComponentRoscob4_3AcePortFactory();
	virtual ~ComponentRoscob4_3AcePortFactory();

	virtual void initialize(ComponentRoscob4_3 *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	virtual Smart::IPushClientPattern<CommBasicObjects::CommJoystick> * createJoyIn() override;
	
	
	// get a pointer to the internal component implementation
	SmartACE::SmartComponent* getComponentImpl();

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* COMPONENTROSCOB4_3_ACE_PORTFACTORY_HH_ */
