//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_NAV_MSGS_ODOMETRY_H_
#define ROSCOMMON_MSGS_NAV_MSGS_ODOMETRY_H_

#include "ROSCommon_msgs/Nav_msgs_OdometryCore.hh"

namespace ROSCommon_msgs {
		
class Nav_msgs_Odometry : public Nav_msgs_OdometryCore {
	public:
		// default constructors
		Nav_msgs_Odometry();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// Nav_msgs_Odometry(const ROSRos_core::Std_msgs_Header &header, const std::string &child_frame_id, const ROSCommon_msgs::Geometry_msgs_PoseWithCovariance &pose, const ROSCommon_msgs::Geometry_msgs_TwistWithCovariance &twist);
		
		Nav_msgs_Odometry(const Nav_msgs_OdometryCore &nav_msgs_Odometry);
		Nav_msgs_Odometry(const DATATYPE &nav_msgs_Odometry);
		virtual ~Nav_msgs_Odometry();
		
		// use framework specific getter and setter methods from core (base) class
		using Nav_msgs_OdometryCore::get;
		using Nav_msgs_OdometryCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const Nav_msgs_Odometry &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace ROSCommon_msgs */
#endif /* ROSCOMMON_MSGS_NAV_MSGS_ODOMETRY_H_ */
