//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "ROSCommon_msgs/Nav_msgs_GetMapActionResult.hh"

using namespace ROSCommon_msgs;

Nav_msgs_GetMapActionResult::Nav_msgs_GetMapActionResult()
:	Nav_msgs_GetMapActionResultCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
Nav_msgs_GetMapActionResult::Nav_msgs_GetMapActionResult(const ROSRos_core::Std_msgs_Header &header, const ROSCommon_msgs::Actionlib_msgs_GoalStatus &status, const ROSCommon_msgs::Nav_msgs_GetMapResult &result)
:	Nav_msgs_GetMapActionResultCore() // base constructor sets default values as defined in the model
{
	setHeader(header);
	setStatus(status);
	setResult(result);
}
 */

Nav_msgs_GetMapActionResult::Nav_msgs_GetMapActionResult(const Nav_msgs_GetMapActionResultCore &nav_msgs_GetMapActionResult)
:	Nav_msgs_GetMapActionResultCore(nav_msgs_GetMapActionResult)
{  }

Nav_msgs_GetMapActionResult::Nav_msgs_GetMapActionResult(const DATATYPE &nav_msgs_GetMapActionResult)
:	Nav_msgs_GetMapActionResultCore(nav_msgs_GetMapActionResult)
{  }

Nav_msgs_GetMapActionResult::~Nav_msgs_GetMapActionResult()
{  }
