//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_SENSOR_MSGS_LASERECHO_H_
#define ROSCOMMON_MSGS_SENSOR_MSGS_LASERECHO_H_

#include "ROSCommon_msgs/Sensor_msgs_LaserEchoCore.hh"

namespace ROSCommon_msgs {
		
class Sensor_msgs_LaserEcho : public Sensor_msgs_LaserEchoCore {
	public:
		// default constructors
		Sensor_msgs_LaserEcho();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// Sensor_msgs_LaserEcho(const std::vector<float> &echoes);
		
		Sensor_msgs_LaserEcho(const Sensor_msgs_LaserEchoCore &sensor_msgs_LaserEcho);
		Sensor_msgs_LaserEcho(const DATATYPE &sensor_msgs_LaserEcho);
		virtual ~Sensor_msgs_LaserEcho();
		
		// use framework specific getter and setter methods from core (base) class
		using Sensor_msgs_LaserEchoCore::get;
		using Sensor_msgs_LaserEchoCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const Sensor_msgs_LaserEcho &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace ROSCommon_msgs */
#endif /* ROSCOMMON_MSGS_SENSOR_MSGS_LASERECHO_H_ */
