//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "ROSCommon_msgs/Visualization_msgs_InteractiveMarkerInit.hh"

using namespace ROSCommon_msgs;

Visualization_msgs_InteractiveMarkerInit::Visualization_msgs_InteractiveMarkerInit()
:	Visualization_msgs_InteractiveMarkerInitCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
Visualization_msgs_InteractiveMarkerInit::Visualization_msgs_InteractiveMarkerInit(const std::string &server_id, const unsigned long int &seq_num, const std::vector<ROSCommon_msgs::Visualization_msgs_InteractiveMarker> &markers)
:	Visualization_msgs_InteractiveMarkerInitCore() // base constructor sets default values as defined in the model
{
	setServer_id(server_id);
	setSeq_num(seq_num);
	setMarkers(markers);
}
 */

Visualization_msgs_InteractiveMarkerInit::Visualization_msgs_InteractiveMarkerInit(const Visualization_msgs_InteractiveMarkerInitCore &visualization_msgs_InteractiveMarkerInit)
:	Visualization_msgs_InteractiveMarkerInitCore(visualization_msgs_InteractiveMarkerInit)
{  }

Visualization_msgs_InteractiveMarkerInit::Visualization_msgs_InteractiveMarkerInit(const DATATYPE &visualization_msgs_InteractiveMarkerInit)
:	Visualization_msgs_InteractiveMarkerInitCore(visualization_msgs_InteractiveMarkerInit)
{  }

Visualization_msgs_InteractiveMarkerInit::~Visualization_msgs_InteractiveMarkerInit()
{  }
