//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _TIMESERVICEIN_UPCALL_MANAGER_HH
#define _TIMESERVICEIN_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "TimeServiceInUpcallInterface.hh"

/** TimeServiceInUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort TimeServiceIn and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class TimeServiceInUpcallManager
:	public Smart::IInputHandler<DomainHelloServices::CommTime>
{
private:
	// list of associated updalls
	std::list<TimeServiceInUpcallInterface*> upcalls;

	// call the on_TimeServiceIn of all the attached TimeServiceInUpcallInterfaces
	void notify_upcalls(const DomainHelloServices::CommTime &input);
	
protected:
	virtual void handle_input(const DomainHelloServices::CommTime &input) {
		// relay input-handling to all attached TimeServiceInUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	TimeServiceInUpcallManager(
		Smart::InputSubject<DomainHelloServices::CommTime> *subject,
		const int &prescaleFactor=1
	);
	virtual ~TimeServiceInUpcallManager();
	
	void attach(TimeServiceInUpcallInterface *upcall);
	void detach(TimeServiceInUpcallInterface *upcall);
};

#endif
