//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_ACTIONLIB_MSGS_GOALSTATUS_DATA_H_
#define ROSCOMMON_MSGS_ACTIONLIB_MSGS_GOALSTATUS_DATA_H_

#include "ROSCommon_msgs/Actionlib_msgs_GoalIDData.hh"

#include <string>

namespace ROSCommon_msgsIDL 
{
	struct Actionlib_msgs_GoalStatus
	{
		ROSCommon_msgsIDL::Actionlib_msgs_GoalID goal_id;
		unsigned char status;
		std::string text;
  	};
};

#endif /* ROSCOMMON_MSGS_ACTIONLIB_MSGS_GOALSTATUS_DATA_H_ */
