//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_SENSOR_MSGS_BATTERYSTATETYPE_ENUM_H_
#define ROSCOMMON_MSGS_SENSOR_MSGS_BATTERYSTATETYPE_ENUM_H_

#include <ROSCommon_msgs/enumSensor_msgs_BatteryStateTypeData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace ROSCommon_msgs {
	
	class Sensor_msgs_BatteryStateType {
	private:
		ROSCommon_msgsIDL::Sensor_msgs_BatteryStateType value;
		
	public:
		enum ENUM_Sensor_msgs_BatteryStateType {
			ENUM_VALUE_UNDEFINED = 0,
			POWER_SUPPLY_STATUS_UNKNOWN = 1,
			POWER_SUPPLY_STATUS_CHARGING = 2,
			POWER_SUPPLY_STATUS_DISCHARGING = 3,
			POWER_SUPPLY_STATUS_NOT_CHARGING = 4,
			POWER_SUPPLY_STATUS_FULL = 5,
			POWER_SUPPLY_HEALTH_UNKNOWN = 6,
			POWER_SUPPLY_HEALTH_GOOD = 7,
			POWER_SUPPLY_HEALTH_OVERHEAT = 8,
			POWER_SUPPLY_HEALTH_DEAD = 9,
			POWER_SUPPLY_HEALTH_OVERVOLTAGE = 10,
			POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 11,
			POWER_SUPPLY_HEALTH_COLD = 12,
			POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 13,
			POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 14,
			POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 15,
			POWER_SUPPLY_TECHNOLOGY_NIMH = 16,
			POWER_SUPPLY_TECHNOLOGY_LION = 17,
			POWER_SUPPLY_TECHNOLOGY_LIPO = 18,
			POWER_SUPPLY_TECHNOLOGY_LIFE = 19,
			POWER_SUPPLY_TECHNOLOGY_NICD = 20,
			POWER_SUPPLY_TECHNOLOGY_LIMN = 21
		};
		
		// default constructor
		Sensor_msgs_BatteryStateType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		Sensor_msgs_BatteryStateType(ENUM_Sensor_msgs_BatteryStateType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		Sensor_msgs_BatteryStateType(ROSCommon_msgsIDL::Sensor_msgs_BatteryStateType e) {
			value = e;
		}
		
		//const ROSCommon_msgsIDL::Sensor_msgs_BatteryStateType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_Sensor_msgs_BatteryStateType() const {
			return static_cast<ENUM_Sensor_msgs_BatteryStateType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_Sensor_msgs_BatteryStateType t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case POWER_SUPPLY_STATUS_UNKNOWN:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_STATUS_UNKNOWN";
					break;
				case POWER_SUPPLY_STATUS_CHARGING:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_STATUS_CHARGING";
					break;
				case POWER_SUPPLY_STATUS_DISCHARGING:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_STATUS_DISCHARGING";
					break;
				case POWER_SUPPLY_STATUS_NOT_CHARGING:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_STATUS_NOT_CHARGING";
					break;
				case POWER_SUPPLY_STATUS_FULL:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_STATUS_FULL";
					break;
				case POWER_SUPPLY_HEALTH_UNKNOWN:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_UNKNOWN";
					break;
				case POWER_SUPPLY_HEALTH_GOOD:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_GOOD";
					break;
				case POWER_SUPPLY_HEALTH_OVERHEAT:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_OVERHEAT";
					break;
				case POWER_SUPPLY_HEALTH_DEAD:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_DEAD";
					break;
				case POWER_SUPPLY_HEALTH_OVERVOLTAGE:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_OVERVOLTAGE";
					break;
				case POWER_SUPPLY_HEALTH_UNSPEC_FAILURE:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_UNSPEC_FAILURE";
					break;
				case POWER_SUPPLY_HEALTH_COLD:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_COLD";
					break;
				case POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE";
					break;
				case POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE";
					break;
				case POWER_SUPPLY_TECHNOLOGY_UNKNOWN:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_TECHNOLOGY_UNKNOWN";
					break;
				case POWER_SUPPLY_TECHNOLOGY_NIMH:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_TECHNOLOGY_NIMH";
					break;
				case POWER_SUPPLY_TECHNOLOGY_LION:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_TECHNOLOGY_LION";
					break;
				case POWER_SUPPLY_TECHNOLOGY_LIPO:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_TECHNOLOGY_LIPO";
					break;
				case POWER_SUPPLY_TECHNOLOGY_LIFE:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_TECHNOLOGY_LIFE";
					break;
				case POWER_SUPPLY_TECHNOLOGY_NICD:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_TECHNOLOGY_NICD";
					break;
				case POWER_SUPPLY_TECHNOLOGY_LIMN:
					result = "Sensor_msgs_BatteryStateType::POWER_SUPPLY_TECHNOLOGY_LIMN";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const Sensor_msgs_BatteryStateType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
