//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_ACTIONLIB_MSGS_GOALSTATUSTYPE_ENUM_H_
#define ROSCOMMON_MSGS_ACTIONLIB_MSGS_GOALSTATUSTYPE_ENUM_H_

#include <ROSCommon_msgs/enumActionlib_msgs_GoalStatusTypeData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace ROSCommon_msgs {
	
	class Actionlib_msgs_GoalStatusType {
	private:
		ROSCommon_msgsIDL::Actionlib_msgs_GoalStatusType value;
		
	public:
		enum ENUM_Actionlib_msgs_GoalStatusType {
			ENUM_VALUE_UNDEFINED = 0,
			PENDING = 1,
			ACTIVE = 2,
			PREEMPTED = 3,
			SUCCEEDED = 4,
			ABORTED = 5,
			REJECTED = 6,
			PREEMPTING = 7,
			RECALLING = 8,
			RECALLED = 9,
			LOST = 10
		};
		
		// default constructor
		Actionlib_msgs_GoalStatusType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		Actionlib_msgs_GoalStatusType(ENUM_Actionlib_msgs_GoalStatusType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		Actionlib_msgs_GoalStatusType(ROSCommon_msgsIDL::Actionlib_msgs_GoalStatusType e) {
			value = e;
		}
		
		//const ROSCommon_msgsIDL::Actionlib_msgs_GoalStatusType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_Actionlib_msgs_GoalStatusType() const {
			return static_cast<ENUM_Actionlib_msgs_GoalStatusType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_Actionlib_msgs_GoalStatusType t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case PENDING:
					result = "Actionlib_msgs_GoalStatusType::PENDING";
					break;
				case ACTIVE:
					result = "Actionlib_msgs_GoalStatusType::ACTIVE";
					break;
				case PREEMPTED:
					result = "Actionlib_msgs_GoalStatusType::PREEMPTED";
					break;
				case SUCCEEDED:
					result = "Actionlib_msgs_GoalStatusType::SUCCEEDED";
					break;
				case ABORTED:
					result = "Actionlib_msgs_GoalStatusType::ABORTED";
					break;
				case REJECTED:
					result = "Actionlib_msgs_GoalStatusType::REJECTED";
					break;
				case PREEMPTING:
					result = "Actionlib_msgs_GoalStatusType::PREEMPTING";
					break;
				case RECALLING:
					result = "Actionlib_msgs_GoalStatusType::RECALLING";
					break;
				case RECALLED:
					result = "Actionlib_msgs_GoalStatusType::RECALLED";
					break;
				case LOST:
					result = "Actionlib_msgs_GoalStatusType::LOST";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const Actionlib_msgs_GoalStatusType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
