//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ROSCommon_msgs/Geometry_msgs_QuaternionCore.hh"

// serialization/deserialization operators
//#include "ROSCommon_msgs/Geometry_msgs_QuaternionACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace ROSCommon_msgs 
{
	const char* Geometry_msgs_QuaternionCore::getCompiledHash()
	{
		return ROSCommon_msgsIDL::REPO_HASH;
	}
	
	void Geometry_msgs_QuaternionCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void Geometry_msgs_QuaternionCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "Geometry_msgs_QuaternionCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t Geometry_msgs_QuaternionCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.x);
		boost::hash_combine(seed, data.y);
		boost::hash_combine(seed, data.z);
		boost::hash_combine(seed, data.w);
		
		return seed;
	}
	#endif
	
	// default constructor
	Geometry_msgs_QuaternionCore::Geometry_msgs_QuaternionCore()
	:	idl_Geometry_msgs_Quaternion()
	{  
		setX(0.0);
		setY(0.0);
		setZ(0.0);
		setW(0.0);
	}
	
	Geometry_msgs_QuaternionCore::Geometry_msgs_QuaternionCore(const DATATYPE &data)
	:	idl_Geometry_msgs_Quaternion(data)
	{  }

	Geometry_msgs_QuaternionCore::~Geometry_msgs_QuaternionCore()
	{  }
	
	void Geometry_msgs_QuaternionCore::to_ostream(std::ostream &os) const
	{
	  os << "Geometry_msgs_Quaternion(";
	  os << getX() << " ";
	  os << getY() << " ";
	  os << getZ() << " ";
	  os << getW() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void Geometry_msgs_QuaternionCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<x>" << getX() << "</x>";
		os << indent << "<y>" << getY() << "</y>";
		os << indent << "<z>" << getZ() << "</z>";
		os << indent << "<w>" << getW() << "</w>";
	}
	
	// restore from xml stream
	void Geometry_msgs_QuaternionCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_x("<x>");
		static const Smart::KnuthMorrisPratt kmp_y("<y>");
		static const Smart::KnuthMorrisPratt kmp_z("<z>");
		static const Smart::KnuthMorrisPratt kmp_w("<w>");
		
		if(kmp_x.search(is)) {
			double xItem;
			is >> xItem;
			setX(xItem);
		}
		if(kmp_y.search(is)) {
			double yItem;
			is >> yItem;
			setY(yItem);
		}
		if(kmp_z.search(is)) {
			double zItem;
			is >> zItem;
			setZ(zItem);
		}
		if(kmp_w.search(is)) {
			double wItem;
			is >> wItem;
			setW(wItem);
		}
	}
	
	/*
	void Geometry_msgs_QuaternionCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		ROSCommon_msgsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(ROSCommon_msgsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see Geometry_msgs_QuaternionACE.hh)
		cdr << idl_Geometry_msgs_Quaternion;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_Geometry_msgs_Quaternion);
		cdr << data_hash;
		// std::cout << "Geometry_msgs_QuaternionCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void Geometry_msgs_QuaternionCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		ROSCommon_msgsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see Geometry_msgs_QuaternionACE.hh)
		cdr >> idl_Geometry_msgs_Quaternion;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_Geometry_msgs_Quaternion);
		assert(data_hash == own_hash);
		// std::cout << "Geometry_msgs_QuaternionCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace ROSCommon_msgs */
