//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_GEOMETRY_MSGS_POSEWITHCOVARIANCE_ACE_H_
#define ROSCOMMON_MSGS_GEOMETRY_MSGS_POSEWITHCOVARIANCE_ACE_H_

#include "ROSCommon_msgs/Geometry_msgs_PoseWithCovariance.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure Geometry_msgs_PoseWithCovariance
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSCommon_msgsIDL::Geometry_msgs_PoseWithCovariance &data);

// de-serialization operator for DataStructure Geometry_msgs_PoseWithCovariance
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSCommon_msgsIDL::Geometry_msgs_PoseWithCovariance &data);

// serialization operator for CommunicationObject Geometry_msgs_PoseWithCovariance
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSCommon_msgs::Geometry_msgs_PoseWithCovariance &obj);

// de-serialization operator for CommunicationObject Geometry_msgs_PoseWithCovariance
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSCommon_msgs::Geometry_msgs_PoseWithCovariance &obj);

#endif /* ROSCOMMON_MSGS_GEOMETRY_MSGS_POSEWITHCOVARIANCE_ACE_H_ */
