//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_NAV_MSGS_PATH_CORE_H_
#define ROSCOMMON_MSGS_NAV_MSGS_PATH_CORE_H_

#include "ROSCommon_msgs/Nav_msgs_PathData.hh"
#include "ROSCommon_msgs/Geometry_msgs_PoseStamped.hh"
#include "ROSRos_core/Std_msgs_Header.hh"

#include <iostream>
#include <string>
#include <list>

namespace ROSCommon_msgs {
	
class Nav_msgs_PathCore {
protected:
	// data structure
	ROSCommon_msgsIDL::Nav_msgs_Path idl_Nav_msgs_Path;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef ROSCommon_msgsIDL::Nav_msgs_Path DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	Nav_msgs_PathCore();
	Nav_msgs_PathCore(const DATATYPE &data);
	// default destructor
	virtual ~Nav_msgs_PathCore();
	
	const DATATYPE& get() const { return idl_Nav_msgs_Path; }
	operator const DATATYPE&() const { return idl_Nav_msgs_Path; }
	DATATYPE& set() { return idl_Nav_msgs_Path; }

	static inline std::string identifier(void) { return "ROSCommon_msgs::Nav_msgs_Path"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Header
	inline ROSRos_core::Std_msgs_Header getHeader() const { return ROSRos_core::Std_msgs_Header(idl_Nav_msgs_Path.header); }
	inline Nav_msgs_PathCore& setHeader(const ROSRos_core::Std_msgs_Header &header) { idl_Nav_msgs_Path.header = header; return *this; }
	
	// getter and setter for element Poses
	/**
	 * Getter methods for element idl_Nav_msgs_Path.poses of type vector<ROSCommon_msgs::Geometry_msgs_PoseStamped>
	 */
	inline std::vector<ROSCommon_msgs::Geometry_msgs_PoseStamped> getPosesCopy() const { 
		return std::vector<ROSCommon_msgs::Geometry_msgs_PoseStamped>(idl_Nav_msgs_Path.poses.begin(), idl_Nav_msgs_Path.poses.end());
	}
	inline ROSCommon_msgs::Geometry_msgs_PoseStamped getPosesElemAtPos(const size_t &pos) const {
		return ROSCommon_msgs::Geometry_msgs_PoseStamped(idl_Nav_msgs_Path.poses[pos]);
	}
	inline size_t getPosesSize() const { return idl_Nav_msgs_Path.poses.size(); }
	inline bool isPosesEmpty() const { return idl_Nav_msgs_Path.poses.empty(); }
	/**
	 * Setter methods for idl_Nav_msgs_Path.poses of type vector<ROSCommon_msgs::Geometry_msgs_PoseStamped>
	 */
	inline Nav_msgs_PathCore& setPoses(const std::vector<ROSCommon_msgs::Geometry_msgs_PoseStamped> &poses) { 
		idl_Nav_msgs_Path.poses.assign(poses.begin(), poses.end());
		return *this;
	}
	inline bool setPosesElemAtPos(const size_t &pos, const ROSCommon_msgs::Geometry_msgs_PoseStamped &elem) {
		if(pos < idl_Nav_msgs_Path.poses.size()) {
			idl_Nav_msgs_Path.poses[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertPosesVectorAtPos(const size_t &pos, const std::vector<ROSCommon_msgs::Geometry_msgs_PoseStamped> &data) {
		if(pos < idl_Nav_msgs_Path.poses.size()) {
			idl_Nav_msgs_Path.poses.insert(idl_Nav_msgs_Path.poses.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizePoses(const size_t &size) { idl_Nav_msgs_Path.poses.resize(size); }
	inline bool erasePosesElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_Nav_msgs_Path.poses.size() ) {
			idl_Nav_msgs_Path.poses.erase(idl_Nav_msgs_Path.poses.begin()+pos, idl_Nav_msgs_Path.poses.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearPoses() { idl_Nav_msgs_Path.poses.clear(); }
};

} /* namespace ROSCommon_msgs */
#endif /* ROSCOMMON_MSGS_NAV_MSGS_PATH_CORE_H_ */
