//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ROSCommon_msgs/Nav_msgs_OccupancyGridACE.hh"
#include <ace/SString.h>
#include "ROSCommon_msgs/Nav_msgs_MapMetaDataACE.hh"
#include "ROSRos_core/Std_msgs_HeaderACE.hh"

// serialization operator for element Nav_msgs_OccupancyGrid
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSCommon_msgsIDL::Nav_msgs_OccupancyGrid &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element header
	good_bit = good_bit && cdr << data.header;
	// serialize list-element info
	good_bit = good_bit && cdr << data.info;
	// serialize list-element data
	good_bit = good_bit && cdr << ACE_Utils::truncate_cast<ACE_CDR::ULong>(data.data.size());
	good_bit = good_bit && cdr.write_char_array(data.data.data(), data.data.size());
	
	return good_bit;
}

// de-serialization operator for element Nav_msgs_OccupancyGrid
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSCommon_msgsIDL::Nav_msgs_OccupancyGrid &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element header
	good_bit = good_bit && cdr >> data.header;
	// deserialize type element info
	good_bit = good_bit && cdr >> data.info;
	// deserialize list-type element data
	ACE_CDR::ULong data_dataNbr;
	good_bit = good_bit && cdr >> data_dataNbr;
	data.data.resize(data_dataNbr);
	good_bit = good_bit && cdr.read_char_array(data.data.data(), data_dataNbr);
	
	return good_bit;
}

// serialization operator for CommunicationObject Nav_msgs_OccupancyGrid
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const ROSCommon_msgs::Nav_msgs_OccupancyGrid &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject Nav_msgs_OccupancyGrid
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, ROSCommon_msgs::Nav_msgs_OccupancyGrid &obj)
{
	return cdr >> obj.set();
}
