//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ROSCommon_msgs/Sensor_msgs_ChannelFloat32Core.hh"

// serialization/deserialization operators
//#include "ROSCommon_msgs/Sensor_msgs_ChannelFloat32ACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace ROSCommon_msgs 
{
	const char* Sensor_msgs_ChannelFloat32Core::getCompiledHash()
	{
		return ROSCommon_msgsIDL::REPO_HASH;
	}
	
	void Sensor_msgs_ChannelFloat32Core::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void Sensor_msgs_ChannelFloat32Core::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "Sensor_msgs_ChannelFloat32Core hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t Sensor_msgs_ChannelFloat32Core::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, std::string(data.name.c_str()));
		std::vector<ACE_CDR::Float>::const_iterator data_valuesIt;
		for(data_valuesIt=data.values.begin(); data_valuesIt!=data.values.end(); data_valuesIt++) {
			boost::hash_combine(seed, *data_valuesIt);
		}
		
		return seed;
	}
	#endif
	
	// default constructor
	Sensor_msgs_ChannelFloat32Core::Sensor_msgs_ChannelFloat32Core()
	:	idl_Sensor_msgs_ChannelFloat32()
	{  
		setName("");
		setValues(std::vector<float>());
	}
	
	Sensor_msgs_ChannelFloat32Core::Sensor_msgs_ChannelFloat32Core(const DATATYPE &data)
	:	idl_Sensor_msgs_ChannelFloat32(data)
	{  }

	Sensor_msgs_ChannelFloat32Core::~Sensor_msgs_ChannelFloat32Core()
	{  }
	
	void Sensor_msgs_ChannelFloat32Core::to_ostream(std::ostream &os) const
	{
	  os << "Sensor_msgs_ChannelFloat32(";
	  os << getName() << " ";
	  std::vector<float>::const_iterator valuesIt;
	  std::vector<float> valuesList = getValuesCopy();
	  for(valuesIt=valuesList.begin(); valuesIt!=valuesList.end(); valuesIt++) {
	  	os << *valuesIt << " ";
	  }
	  os << ") ";
	}
	
	// convert to xml stream
	void Sensor_msgs_ChannelFloat32Core::to_xml(std::ostream &os, const std::string &indent) const {
		size_t counter = 0;
		
		os << indent << "<name>" << getName() << "</name>";
		std::vector<float>::const_iterator valuesIt;
		std::vector<float> valuesList = getValuesCopy();
		counter = 0;
		os << indent << "<valuesList n=\"" << valuesList.size() << "\">";
		for(valuesIt=valuesList.begin(); valuesIt!=valuesList.end(); valuesIt++) {
			os << indent << "<values i=\"" << counter++ << "\">" << *valuesIt << "</values>";
		}
		os << indent << "</valuesList>";
	}
	
	// restore from xml stream
	void Sensor_msgs_ChannelFloat32Core::from_xml(std::istream &is) {
		size_t counter = 0;
		
		static const Smart::KnuthMorrisPratt kmp_name("<name>");
		static const Smart::KnuthMorrisPratt kmp_valuesList("<valuesList n=\"");
		static const Smart::KnuthMorrisPratt kmp_values("\">");
		
		if(kmp_name.search(is)) {
			std::string nameItem;
			is >> nameItem;
			setName(nameItem);
		}
		if(kmp_valuesList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			float valuesItem;
			std::vector<float> valuesList;
			kmp_values.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_values.search(is)) {
					is >> valuesItem;
					valuesList.push_back(valuesItem);
				}
			}
			setValues(valuesList);
		}
	}
	
	/*
	void Sensor_msgs_ChannelFloat32Core::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		ROSCommon_msgsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(ROSCommon_msgsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see Sensor_msgs_ChannelFloat32ACE.hh)
		cdr << idl_Sensor_msgs_ChannelFloat32;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_Sensor_msgs_ChannelFloat32);
		cdr << data_hash;
		// std::cout << "Sensor_msgs_ChannelFloat32Core: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void Sensor_msgs_ChannelFloat32Core::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		ROSCommon_msgsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see Sensor_msgs_ChannelFloat32ACE.hh)
		cdr >> idl_Sensor_msgs_ChannelFloat32;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_Sensor_msgs_ChannelFloat32);
		assert(data_hash == own_hash);
		// std::cout << "Sensor_msgs_ChannelFloat32Core: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace ROSCommon_msgs */
