//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_SENSOR_MSGS_LASERECHO_DATA_H_
#define ROSCOMMON_MSGS_SENSOR_MSGS_LASERECHO_DATA_H_


#include <vector>

namespace ROSCommon_msgsIDL 
{
	typedef std::vector<float> Sensor_msgs_LaserEcho_echoes_type;
	struct Sensor_msgs_LaserEcho
	{
		Sensor_msgs_LaserEcho_echoes_type echoes;
  	};
};

#endif /* ROSCOMMON_MSGS_SENSOR_MSGS_LASERECHO_DATA_H_ */
