//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_SENSOR_MSGS_TEMPERATURE_CORE_H_
#define ROSCOMMON_MSGS_SENSOR_MSGS_TEMPERATURE_CORE_H_

#include "ROSCommon_msgs/Sensor_msgs_TemperatureData.hh"
#include "ROSRos_core/Std_msgs_Header.hh"

#include <iostream>
#include <string>
#include <list>

namespace ROSCommon_msgs {
	
class Sensor_msgs_TemperatureCore {
protected:
	// data structure
	ROSCommon_msgsIDL::Sensor_msgs_Temperature idl_Sensor_msgs_Temperature;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef ROSCommon_msgsIDL::Sensor_msgs_Temperature DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	Sensor_msgs_TemperatureCore();
	Sensor_msgs_TemperatureCore(const DATATYPE &data);
	// default destructor
	virtual ~Sensor_msgs_TemperatureCore();
	
	const DATATYPE& get() const { return idl_Sensor_msgs_Temperature; }
	operator const DATATYPE&() const { return idl_Sensor_msgs_Temperature; }
	DATATYPE& set() { return idl_Sensor_msgs_Temperature; }

	static inline std::string identifier(void) { return "ROSCommon_msgs::Sensor_msgs_Temperature"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Header
	inline ROSRos_core::Std_msgs_Header getHeader() const { return ROSRos_core::Std_msgs_Header(idl_Sensor_msgs_Temperature.header); }
	inline Sensor_msgs_TemperatureCore& setHeader(const ROSRos_core::Std_msgs_Header &header) { idl_Sensor_msgs_Temperature.header = header; return *this; }
	
	// getter and setter for element Temperature
	inline double getTemperature() const { return idl_Sensor_msgs_Temperature.temperature; }
	inline Sensor_msgs_TemperatureCore& setTemperature(const double &temperature) { idl_Sensor_msgs_Temperature.temperature = temperature; return *this; }
	
	// getter and setter for element Variance
	inline double getVariance() const { return idl_Sensor_msgs_Temperature.variance; }
	inline Sensor_msgs_TemperatureCore& setVariance(const double &variance) { idl_Sensor_msgs_Temperature.variance = variance; return *this; }
};

} /* namespace ROSCommon_msgs */
#endif /* ROSCOMMON_MSGS_SENSOR_MSGS_TEMPERATURE_CORE_H_ */
