//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef ROSCOMMON_MSGS_SHAPE_MSGS_MESHTRIANGLE_CORE_H_
#define ROSCOMMON_MSGS_SHAPE_MSGS_MESHTRIANGLE_CORE_H_

#include "ROSCommon_msgs/Shape_msgs_MeshTriangleData.hh"

#include <iostream>
#include <string>
#include <list>

namespace ROSCommon_msgs {
	
class Shape_msgs_MeshTriangleCore {
protected:
	// data structure
	ROSCommon_msgsIDL::Shape_msgs_MeshTriangle idl_Shape_msgs_MeshTriangle;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef ROSCommon_msgsIDL::Shape_msgs_MeshTriangle DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	Shape_msgs_MeshTriangleCore();
	Shape_msgs_MeshTriangleCore(const DATATYPE &data);
	// default destructor
	virtual ~Shape_msgs_MeshTriangleCore();
	
	const DATATYPE& get() const { return idl_Shape_msgs_MeshTriangle; }
	operator const DATATYPE&() const { return idl_Shape_msgs_MeshTriangle; }
	DATATYPE& set() { return idl_Shape_msgs_MeshTriangle; }

	static inline std::string identifier(void) { return "ROSCommon_msgs::Shape_msgs_MeshTriangle"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Vertex_indices
	/**
	 * Getter methods for idl_Shape_msgs_MeshTriangle.vertex_indices of type vector<unsigned int>
	 */
	inline std::vector<unsigned int>& getVertex_indicesRef() { return idl_Shape_msgs_MeshTriangle.vertex_indices; }
	inline std::vector<unsigned int> getVertex_indicesCopy() const {
		return std::vector<unsigned int>(idl_Shape_msgs_MeshTriangle.vertex_indices.begin(), idl_Shape_msgs_MeshTriangle.vertex_indices.end());
	}
	inline unsigned int getVertex_indicesElemAtPos(const size_t &pos) const { return idl_Shape_msgs_MeshTriangle.vertex_indices[pos]; }
	inline size_t getVertex_indicesSize() const { return idl_Shape_msgs_MeshTriangle.vertex_indices.size(); }
	inline bool isVertex_indicesEmpty() const { return idl_Shape_msgs_MeshTriangle.vertex_indices.empty(); }
	/**
	 * Setter methods for idl_Shape_msgs_MeshTriangle.vertex_indices of type vector<unsigned int>
	 */
	inline Shape_msgs_MeshTriangleCore& setVertex_indices(const std::vector<unsigned int> &vertex_indices) { idl_Shape_msgs_MeshTriangle.vertex_indices = vertex_indices; return *this; }
	inline bool setVertex_indicesElemAtPos(const size_t &pos, const unsigned int &elem) {
		if(pos < idl_Shape_msgs_MeshTriangle.vertex_indices.size()) {
			idl_Shape_msgs_MeshTriangle.vertex_indices[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertVertex_indicesVectorAtPos(const size_t &pos, const std::vector<unsigned int> &data) {
		if(pos < idl_Shape_msgs_MeshTriangle.vertex_indices.size()) {
			idl_Shape_msgs_MeshTriangle.vertex_indices.insert(idl_Shape_msgs_MeshTriangle.vertex_indices.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizeVertex_indices(const size_t &size) { idl_Shape_msgs_MeshTriangle.vertex_indices.resize(size); }
	inline bool eraseVertex_indicesElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_Shape_msgs_MeshTriangle.vertex_indices.size() ) {
			idl_Shape_msgs_MeshTriangle.vertex_indices.erase(idl_Shape_msgs_MeshTriangle.vertex_indices.begin()+pos, idl_Shape_msgs_MeshTriangle.vertex_indices.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearVertex_indices() { idl_Shape_msgs_MeshTriangle.vertex_indices.clear(); }
};

} /* namespace ROSCommon_msgs */
#endif /* ROSCOMMON_MSGS_SHAPE_MSGS_MESHTRIANGLE_CORE_H_ */
